### ISSUE TITLE
Does not show SQLite WITHOUT ROWID tables correctly

### ISSUE THREAD

**Issue by stephancb** [saulpw/visidata#1111]
**Small description**

SQLite version 3.8.2 (2013-12-06) and later allow for [WITHOUT ROWID tables](https://www.sqlite.org/withoutrowid.html), which under certain circumstances are more efficient than tables with a rowid. Without rowid tables are not displayed correctly by visidata:

```
[scb@shrike ~]$ sqlite3 example.db
-- Loading resources from /home/scb/.sqliterc
wal
SQLite version 3.36.0 2021-06-18 18:36:39
Enter ".help" for usage hints.
sqlite> CREATE TABLE withrowid(id INTEGER PRIMARY KEY, datum);
sqlite> INSERT INTO withrowid VALUES(1, 'abc');
sqlite> INSERT INTO withrowid VALUES(2, 'xyz');
sqlite> CREATE TABLE withoutrowid(id INTEGER PRIMARY KEY, datum) WITHOUT ROWID;
sqlite> INSERT INTO withoutrowid VALUES(1, 'abc');
sqlite> INSERT INTO withoutrowid VALUES(2, 'xyz');
sqlite> ^D
[scb@shrike ~]$ vd example.db
```

**Expected result**

```
name         ║ rows   #| cols#| keys | source   ║
withrowid    ║       2 |    3 | id    | example ║
withoutrowid ║       2 |    3 | id    | example ║
```

**Actual result**

```
name         ║ rows   #| cols#| keys | source   ║
withrowid    ║       2 |    3 | id    | example ║
withoutrowid ║       0 |    3 | id    | example ║
```
(the withoutrowid table has **0 rows**)

`Ctrl-E`:

```
text
 Traceback (most recent call last):
   File "/usr/lib/python3.9/site-packages/visidata/threads.py", line 219, in _toplevelTryFunc
     t.status = func(*args, **kwargs)
   File "/usr/lib/python3.9/site-packages/visidata/sheets.py", line 289, in reload
     for r in self.iterload():
   File "/usr/lib/python3.9/site-packages/visidata/loaders/sqlite.py", line 55, in iterload
     r = self.execute(conn, 'SELECT rowid, * FROM "%s"' % tblname)
   File "/usr/lib/python3.9/site-packages/visidata/loaders/sqlite.py", line 28, in execute
     return conn.execute(sql, parms)
 sqlite3.OperationalError: no such column: rowid
```

**Additional context**
Please include the version of VisiData: `saul.pw/VisiData v2.5`

**Comment by anjakefala** [comment]
I might be wrong, but I believe this is a known limitation, and that we had a conversation where we decided to accept it for the time being.

**Comment by stephancb** [comment]
Ok, thanks. I could not find any mentioning of the limitation in the documentation. I'm not fluent in python. But a fix could be to not use `rowid` in `File "/usr/lib/python3.9/site-packages/visidata/loaders/sqlite.py"`, instead just iterate over the rows, until `step` returns `SQLITE_DONE` (or the maximum nr of rows to be loaded is reached). If a row index is internally needed, it could be an internal variable. Also in other SQL databases, e.g. Postgres and MySql, tables are not guaranteed to have rowids.

**Comment by saulpw** [comment]
The rowid is necessary to modify the specific row--there may be multiple rows with identical values in every field, and I can't see how to modify fields of different rows with an UPDATE in that case.

The approach you mention could work, and then the `WITHOUT ROWID` tables would be read-only.  Similarly with tables in Postgres/Mysql that don't have rowids.  For now, we can add an entry to visidata.org/limits describing it.

**Comment by stephancb** [comment]
I agree, updating without rowid would be not completley straight-forward, but not impossible:

An SQL table always has a primary key which is unique. If not specified, it is `rowid` (in SQLite). Without rowid it must be specified. The primary key can consist of several columns. Therefore

1. if all columns are available, one can specify all of them, the old values, in the `WHERE` clause of the update. The update then fails if the primary key or other columns with a `UNIQUE` constraint were become non-unique (this can happen also for tables with `rowid`). Otherwise the update should work as intended.
2. It is bit inefficient to specify all columns in the `WHERE` clause, only the primary key one(s) is/are necessary. For `WITHOUT ROWID` tables visidata would need to find out which is the primary key. This is of course possible, for SQLite see (https://stackoverflow.com/questions/10472103/sqlite-query-to-find-primary-keys).

Alternative 1 seems to me good enough for `visidata`, if this should be fixed.

**Comment by anjakefala** [comment]
> The rowid is necessary to modify the specific row-

Right! That was why.

**Comment by anjakefala** [comment]
I think at minimum for v2.6, we can issue a more informative warning ("sqlite tables without rowids are not supported"), and add this to `/limits`.

Thank you for your suggestions!

**Comment by frosencrantz** [comment]
I was actually planning on reporting this issue, but from a different direction. I am seeing it on views.  Sqlite views also don’t have the rowid column, unless added as part of the definition.

I would like to see `SqliteIndexSheet.iterload()` to not ignore the data it is getting from `sqlite_master`.  Also, I think it should add the `type` and `sql` columns even if they are hidden by default. 

Details about what those columns mean are here:
https://www.sqlite.org/schematab.html#interpretation_of_the_schema_table

If the type of the table is `view` then don’t add the rowid by default, also if the SQL statement includes the “without rowid”.  These seem like more useful solutions than creating a limitation VisiData won't read these tables/views:

https://github.com/saulpw/visidata/blob/stable/visidata/loaders/sqlite.py#L122

My preference for a limitation would be if the table doesn’t have the rowid column or the table is a view, don’t allow it to be updated.  I think that is a reasonable limitation, but still allows Visidata to show the data in the table/view. 

Rowid was added in https://github.com/saulpw/visidata/commit/36cf8cbca90d283636aa0929e25a1f986abd4ad4
Before this change, it was possible to look at views, now views are not viewable with Visidata unless they have a rowid column.  This is a bug.

**Comment by stephancb** [comment]
Good point by @frosencrantz I had not stumbled yet over the views yet. No updates

A minor comment, `sqlite_schema` replaces

**Comment by stephancb** [comment]
Sorry, I closed this accidentally. @frosencrantz point is of course valid.

**Comment by saulpw** [comment]
Just so people know, if someone had attached a test db to this bug, it probably would have been fixed by now.  I've bounced off it several times in favor of other issues which were easier to get into.

**Comment by frosencrantz** [comment]
Create a view using sample_data/employees.sqlite:

```
$ sqlite sample_data/employees.sqlite
create view emp_view as select * from emp;
```

**Comment by anjakefala** [comment]
Github does not allow attaching `.db`?? That is annoying.

I uploaded @stephancb's example here: https://github.com/anjakefala/1111_exampledb/blob/master/example.db

**Comment by anjakefala** [comment]
@saulpw has provided a change that accomodates WITHOUT ROWID tables!

They will now be load-able. A current constraint is that users will not be able to save modified tables, which do not contain rowids, to the original database.

This will be available in the next release of VisiData!

**Comment by frosencrantz** [comment]
Thanks for fixing this @saulpw ! And thanks @anjakefala for adding sample data.  And I particularly love that you added `sql` column, I missed that when it first was submitted.

Unfortunately this didn't fix the issue for views, but it didn't fix the issue  for views.  I created https://github.com/saulpw/visidata/issues/1222 .
