### ISSUE TITLE
Disabling motd

### ISSUE THREAD

**Issue by agisty** [saulpw/visidata#190]
Visidata 1.3.1
`~/.visidatarc` contains `options.motd_url = None` as described [in the changelog](https://github.com/saulpw/visidata/blame/569d2177cbb62933508fcc0c18783d4bdffb0094/CHANGELOG.md#L138). I delete the cache `~/.visidata` and run `vd` again but it recreates the file.

On another note, I was surprised to see a TUI data analysis tool making background network requests. Does this need to be enabled by default? What is the policy on retention and usage of network logs? Thank you.

**Comment by saulpw** [comment]
Hi @agisty, thanks for the bug report.  This should have worked but there was a race condition, as the domotd() was being run asynchronously on import, which had a (large) chance of happening before options were parsed.  This is now fixed and will be in v1.4 (scheduled to be released this weekend), so you can disable it as described in the changelog.

As for the background network request, I totally understand your surprise.  Since it is a free utility, the only gratification and motivation I get is knowing that other people are using it, and after the 1.0 release (which was a year of basically full-time effort) I was disappointed that I could not find any indication that anyone was actually using it--even though it had seemingly gotten a lot of exposure via HackerNews.  I was pretty discouraged, but I thought maybe there were a lot of 'silent users', so I spent a lot of time thinking about how to measure usage in a low-impact way.  Aside from restricting downloads (and taking it closed-source), a cute little startup message was the best way I could come up with to get the information I wanted.  This has the added benefit of providing a mechanism for me to send information back to users (like upgrade notices and announcements), since I think most people are casual users and aren't engaged with ongoing development efforts.  So the default is essential for my experience as the developer :)

We won't store individual log entries indefinitely, and we'll add a privacy/retention policy on the website so that this is clear for other people in the future.  (This has been our intent but it hasn't been a priority--thanks for asking the questions and making it a higher priority.)

**Comment by saulpw** [comment]
Replaying this [usage.vd](https://github.com/saulpw/visidata/files/2403884/usage.vd.txt) produces a nice graph with the [usage.tsv](https://visidata.org/usage.tsv), which is updated nightly with the aggregated usage information being collected.

**Comment by agisty** [comment]
Thanks for the quick response!

**Comment by cool-RR** [comment]
This seems to be happening again with the latest version in `develop`. I've set my `.visidatarc` to `options.motd_url = None` but I still get the MOTD. The option value does not change in the options sheet. Beyond fixing this bug, I wish there was a way I could hardcode the MOTD never happening.

**Comment by anjakefala** [comment]
Hey @cool-RR!

I updated the instructions on the privacy page to recommend using `options.motd_url=''` instead. There have been changes in the options tooling since v1.1, and now they are type sensitive. When they get an argument of a different type, they revert back to the default.

Things might get reworked so that `None` is also an acceptable setting, but for now please use `options.motd_url=''`.

**Comment by cool-RR** [comment]
I understand, thank you.
